# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"\x94\x02\n\x0cOrderMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncreated_by\x18\x02 \x01(\t\x12$\n\x06status\x18\x03 \x01(\x0e\x32\x14.OrderMessage.Status\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12*\n\tequipment\x18\x05 \x03(\x0e\x32\x17.OrderMessage.Equipment\"?\n\x06Status\x12\n\n\x06QUEUED\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\"=\n\tEquipment\x12\x0c\n\x08KEYBOARD\x10\x00\x12\t\n\x05MOUSE\x10\x01\x12\n\n\x06WEBCAM\x10\x02\x12\x0b\n\x07MONITOR\x10\x03\"\x07\n\x05\x45mpty\"1\n\x10OrderMessageList\x12\x1d\n\x06orders\x18\x01 \x03(\x0b\x32\r.OrderMessage2X\n\x0cOrderService\x12&\n\x06\x43reate\x12\r.OrderMessage\x1a\r.OrderMessage\x12 \n\x03Get\x12\x06.Empty\x1a\x11.OrderMessageListb\x06proto3')



_ORDERMESSAGE = DESCRIPTOR.message_types_by_name['OrderMessage']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_ORDERMESSAGELIST = DESCRIPTOR.message_types_by_name['OrderMessageList']
_ORDERMESSAGE_STATUS = _ORDERMESSAGE.enum_types_by_name['Status']
_ORDERMESSAGE_EQUIPMENT = _ORDERMESSAGE.enum_types_by_name['Equipment']
OrderMessage = _reflection.GeneratedProtocolMessageType('OrderMessage', (_message.Message,), {
  'DESCRIPTOR' : _ORDERMESSAGE,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderMessage)
  })
_sym_db.RegisterMessage(OrderMessage)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

OrderMessageList = _reflection.GeneratedProtocolMessageType('OrderMessageList', (_message.Message,), {
  'DESCRIPTOR' : _ORDERMESSAGELIST,
  '__module__' : 'order_pb2'
  # @@protoc_insertion_point(class_scope:OrderMessageList)
  })
_sym_db.RegisterMessage(OrderMessageList)

_ORDERSERVICE = DESCRIPTOR.services_by_name['OrderService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDERMESSAGE._serialized_start=16
  _ORDERMESSAGE._serialized_end=292
  _ORDERMESSAGE_STATUS._serialized_start=166
  _ORDERMESSAGE_STATUS._serialized_end=229
  _ORDERMESSAGE_EQUIPMENT._serialized_start=231
  _ORDERMESSAGE_EQUIPMENT._serialized_end=292
  _EMPTY._serialized_start=294
  _EMPTY._serialized_end=301
  _ORDERMESSAGELIST._serialized_start=303
  _ORDERMESSAGELIST._serialized_end=352
  _ORDERSERVICE._serialized_start=354
  _ORDERSERVICE._serialized_end=442
# @@protoc_insertion_point(module_scope)
